version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "stack.yaml"
        "S3_BUCKET": ""
containers:
    LambdaFunctions:
        phases:
            build:
                commands:
                    - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template post-saml.yaml
        artifacts:
            files:
                - post-saml.yaml
